import { randomUUID } from 'node:crypto';
import request from 'supertest';
import { describe, expect, it } from 'vitest';
import { buildTestApp, createTestUser } from '../testUtils.js';
import type { OperationsRepository } from '../repository.js';
import type { Express } from 'express';

const SERVER_ID = '11111111-1111-4111-8111-111111111111';

// Etap 3 replaced the interim X-Admin-Key with local-account sessions
// (see auth.ts) — approve now requires a logged-in 'admin' user.
async function loginAsAdmin(app: Express, repository: OperationsRepository): Promise<request.SuperAgentTest> {
  await createTestUser(repository, 'admin', 'test-password', 'admin');
  const agent = request.agent(app);
  await agent.post('/api/v1/auth/login').send({ username: 'admin', password: 'test-password' });
  return agent;
}

function enrollBody(overrides: Partial<Record<string, unknown>> = {}) {
  return {
    serverId: SERVER_ID,
    institutionCode: '01234567',
    productType: 'LIMS',
    hostname: 'HOUSE-LIMS-01',
    ...overrides,
  };
}

// A1/A2 (Wave 2): the enrollment claim is generated by the ENROLLING
// AGENT, not the server — tests stand in for the agent and mint their
// own opaque claim value, exactly like a real agent would (e.g. a
// GUID).
function generateClaim(): string {
  return `claim_${randomUUID()}`;
}

// D2: bootstrap secret travels only via X-Bootstrap-Secret. A1/A2: the
// claim now travels via X-Enrollment-Claim on POST /enroll too — the
// server never generates or returns one.
function enroll(
  app: Express,
  claim: string | undefined,
  secret = 'test-bootstrap-secret',
  body: Record<string, unknown> = enrollBody(),
) {
  const req = request(app).post('/api/v1/enroll').set('X-Bootstrap-Secret', secret);
  if (claim !== undefined) {
    req.set('X-Enrollment-Claim', claim);
  }
  return req.send(body);
}

function poll(app: Express, serverId: string, claim: string | undefined, secret = 'test-bootstrap-secret') {
  const req = request(app).get(`/api/v1/enroll/${serverId}`).set('X-Bootstrap-Secret', secret);
  if (claim !== undefined) {
    req.set('X-Enrollment-Claim', claim);
  }
  return req;
}

describe('enrollment flow', () => {
  it('rejects an enroll request with the wrong bootstrap secret', async () => {
    const { app } = buildTestApp();
    const res = await enroll(app, generateClaim(), 'wrong');
    expect(res.status).toBe(401);
  });

  it('rejects a POST /enroll with no X-Enrollment-Claim header at all', async () => {
    const { app } = buildTestApp();
    const res = await enroll(app, undefined);
    expect(res.status).toBe(400);
  });

  it('rejects malformed enroll payloads (invalid serverId)', async () => {
    const { app } = buildTestApp();
    const res = await enroll(app, generateClaim(), 'test-bootstrap-secret', enrollBody({ serverId: 'not-a-guid' }));
    expect(res.status).toBe(400);
  });

  // D2: a bootstrapSecret field in the JSON body is no longer the
  // accepted transport — it's simply ignored/absent from the schema,
  // and only the header is checked.
  it('rejects a POST /enroll with the secret in the body but not the header', async () => {
    const { app } = buildTestApp();
    const res = await request(app)
      .post('/api/v1/enroll')
      .set('X-Enrollment-Claim', generateClaim())
      .send({ ...enrollBody(), bootstrapSecret: 'test-bootstrap-secret' });
    expect(res.status).toBe(401);
  });

  it('fresh enroll with an agent-generated claim -> poll succeeds', async () => {
    const { app, repository } = buildTestApp();
    const admin = await loginAsAdmin(app, repository);
    const claim = generateClaim();

    const enrollRes = await enroll(app, claim);
    expect(enrollRes.status).toBe(202);
    expect(enrollRes.body).toEqual({ status: 'pending' });
    // A1/A2: nothing claim-shaped comes back in the response body — the
    // agent already holds its own claim, there's nothing left to reveal.
    expect(enrollRes.body.claimToken).toBeUndefined();

    const pollBeforeApproval = await poll(app, SERVER_ID, claim);
    expect(pollBeforeApproval.body).toEqual({ status: 'pending' });

    const approveRes = await admin.post(`/api/v1/admin/servers/${SERVER_ID}/approve`);
    expect(approveRes.status).toBe(200);
    expect(approveRes.body).toEqual({ status: 'approved' });

    const firstPoll = await poll(app, SERVER_ID, claim);
    expect(firstPoll.body.status).toBe('approved');
    expect(typeof firstPoll.body.apiKey).toBe('string');
    expect(firstPoll.body.apiKey.length).toBeGreaterThan(0);

    // D3: unlike the old reveal-once behavior, a second poll with the
    // SAME claim within the TTL window still returns the key — this is
    // the "lost first response" recovery path.
    const secondPoll = await poll(app, SERVER_ID, claim);
    expect(secondPoll.body.apiKey).toBe(firstPoll.body.apiKey);
  });

  // A7: recovering from a lost POST /enroll response is now just
  // re-POSTing the SAME serverId + SAME claim + SAME metadata the agent
  // already generated locally — no server-side rotation to race with.
  it('retry with the SAME claim (lost response simulation) is idempotent', async () => {
    const { app, repository } = buildTestApp();
    const claim = generateClaim();

    const first = await enroll(app, claim);
    expect(first.status).toBe(202);

    // Simulate "the agent never saw the first response" by simply
    // re-POSTing with identical serverId + claim + metadata.
    const retry = await enroll(app, claim);
    expect(retry.status).toBe(202);
    expect(retry.body).toEqual({ status: 'pending' });

    const server = repository.getServer(SERVER_ID);
    expect(server?.status).toBe('pending');
    expect(server?.hostname).toBe('HOUSE-LIMS-01');

    // The claim still works for the poll afterwards — no duplicate rows,
    // no invalidated claim.
    const pollRes = await poll(app, SERVER_ID, claim);
    expect(pollRes.status).toBe(200);
    expect(pollRes.body).toEqual({ status: 'pending' });
  });

  // THE regression test for the takeover vulnerability found in PR #2
  // review (repository.ts:148, P1): the old code rotated
  // enrollment_claim_hash on every POST /enroll for a pending row and
  // handed the NEW claim back to whoever called it — so an attacker who
  // only knew the fleet bootstrap secret + the victim's serverId (both
  // widely held/visible) could mint themselves a fresh, valid claim for
  // the victim's in-flight enrollment. That rotation path no longer
  // exists: a re-POST with a claim that does not match what's already
  // stored is rejected outright, and the original claim/metadata are
  // left untouched.
  it('rejects a re-enroll with a different claim (takeover attempt)', async () => {
    const { app, repository } = buildTestApp();
    const victimClaim = generateClaim();
    const attackerClaim = generateClaim();

    const victimEnroll = await enroll(app, victimClaim);
    expect(victimEnroll.status).toBe(202);

    const attackerEnroll = await enroll(app, attackerClaim, 'test-bootstrap-secret', enrollBody({ hostname: 'ATTACKER-RENAMED' }));
    expect(attackerEnroll.status).toBe(409);
    expect(attackerEnroll.body).toEqual({ error: 'claim_mismatch' });

    // The victim's row is completely unaffected: same hostname, and the
    // victim's OWN claim still works.
    const server = repository.getServer(SERVER_ID);
    expect(server?.hostname).toBe('HOUSE-LIMS-01');

    const victimPoll = await poll(app, SERVER_ID, victimClaim);
    expect(victimPoll.status).toBe(200);
    expect(victimPoll.body).toEqual({ status: 'pending' });

    // The attacker's fabricated claim never becomes valid for this
    // server.
    const attackerPoll = await poll(app, SERVER_ID, attackerClaim);
    expect(attackerPoll.status).toBe(404);
  });

  // Same scenario as above, phrased as the original threat model:
  // correct bootstrap secret (held fleet-wide) + attacker's own
  // fabricated claim + the victim's real serverId (visible via
  // GET /admin/servers to any admin/viewer) must not grant the attacker
  // anything.
  it('rejects a bootstrap-secret-only takeover attempt against a known victim serverId', async () => {
    const { app, repository } = buildTestApp();
    const victimClaim = generateClaim();
    await enroll(app, victimClaim);

    const attackerClaim = generateClaim();
    const attackerAttempt = await enroll(app, attackerClaim, 'test-bootstrap-secret', enrollBody({ hostname: 'PWNED' }));
    expect(attackerAttempt.status).toBe(409);
    expect(attackerAttempt.body).toEqual({ error: 'claim_mismatch' });

    const server = repository.getServer(SERVER_ID);
    expect(server?.hostname).toBe('HOUSE-LIMS-01');
    expect(server?.status).toBe('pending');

    // The victim can still complete its own enrollment normally.
    const victimPoll = await poll(app, SERVER_ID, victimClaim);
    expect(victimPoll.status).toBe(200);
  });

  // D1/Finding 2: the bootstrap secret alone (no claim) must not be
  // enough to pull an arbitrary enrollment's key, even though it's
  // visible fleet-wide and server GUIDs are visible via admin/servers.
  it('rejects a poll with the correct bootstrap secret but no/wrong enrollment claim', async () => {
    const { app, repository } = buildTestApp();
    const admin = await loginAsAdmin(app, repository);
    const claim = generateClaim();
    await enroll(app, claim);
    await admin.post(`/api/v1/admin/servers/${SERVER_ID}/approve`);

    const noClaim = await poll(app, SERVER_ID, undefined);
    expect(noClaim.status).toBe(404);

    const wrongClaim = await poll(app, SERVER_ID, 'claim_totally-wrong');
    expect(wrongClaim.status).toBe(404);
  });

  // D7: an unknown id and a wrong-claim request against a real id must
  // be indistinguishable.
  it('returns the same 404 shape for an unknown server id and a wrong claim on a real one', async () => {
    const { app, repository } = buildTestApp();
    const admin = await loginAsAdmin(app, repository);
    const claim = generateClaim();
    await enroll(app, claim);
    await admin.post(`/api/v1/admin/servers/${SERVER_ID}/approve`);

    const unknown = await poll(app, '99999999-0000-4000-8000-000000000000', 'claim_whatever');
    const wrongClaim = await poll(app, SERVER_ID, 'claim_whatever');
    expect(unknown.status).toBe(404);
    expect(wrongClaim.status).toBe(404);
    expect(unknown.body).toEqual(wrongClaim.body);
  });

  // A6: a claim that IS valid — just for a DIFFERENT, real server — must
  // 404 exactly like an unknown id or a fabricated claim. Nothing here
  // should let a caller learn "this claim belongs to some other real
  // enrollment" as distinct from "this claim is garbage".
  it('rejects a valid claim for a different server presented against another serverId (cross-server claim)', async () => {
    const { app, repository } = buildTestApp();
    const admin = await loginAsAdmin(app, repository);
    const otherServerId = '22222222-2222-4222-8222-222222222222';

    const claimA = generateClaim();
    const claimB = generateClaim();
    await enroll(app, claimA);
    await enroll(app, claimB, 'test-bootstrap-secret', enrollBody({ serverId: otherServerId, hostname: 'HOUSE-LIMS-02' }));
    await admin.post(`/api/v1/admin/servers/${SERVER_ID}/approve`);
    await admin.post(`/api/v1/admin/servers/${otherServerId}/approve`);

    // claimB is real and valid, but only for otherServerId — presenting
    // it against SERVER_ID must 404, not reveal SERVER_ID's key.
    const crossServerPoll = await poll(app, SERVER_ID, claimB);
    expect(crossServerPoll.status).toBe(404);

    // Sanity: claimB does work against its own server.
    const ownServerPoll = await poll(app, otherServerId, claimB);
    expect(ownServerPoll.status).toBe(200);
    expect(ownServerPoll.body.status).toBe('approved');
  });

  // D6: once a server is approved, a repeat POST /enroll must not
  // silently rewrite its identity fields, and must not succeed at all —
  // it now returns 409, not the old "202, no-op" idempotent response.
  // This holds regardless of which claim is presented (A4).
  it('rejects (409) re-enrolling an already-approved server rather than mutating or resetting it, for any claim', async () => {
    const { app, repository } = buildTestApp();
    const admin = await loginAsAdmin(app, repository);
    const claim = generateClaim();
    await enroll(app, claim);
    await admin.post(`/api/v1/admin/servers/${SERVER_ID}/approve`);

    // Same claim as the original enrollment...
    const reEnrollSameClaim = await enroll(app, claim, 'test-bootstrap-secret', enrollBody({ hostname: 'ATTACKER-RENAMED' }));
    expect(reEnrollSameClaim.status).toBe(409);
    expect(reEnrollSameClaim.body).toEqual({ error: 'already_finalized', status: 'approved' });

    // ...and a completely different one both hit the same locked path,
    // never claim_mismatch — post-finalization, identity is locked
    // independent of claim matching.
    const reEnrollOtherClaim = await enroll(app, generateClaim(), 'test-bootstrap-secret', enrollBody({ hostname: 'ATTACKER-RENAMED-2' }));
    expect(reEnrollOtherClaim.status).toBe(409);
    expect(reEnrollOtherClaim.body).toEqual({ error: 'already_finalized', status: 'approved' });

    const server = repository.getServer(SERVER_ID);
    expect(server?.hostname).toBe('HOUSE-LIMS-01');
  });

  it('rejects (409) re-enrolling an already-revoked server', async () => {
    const { app, repository } = buildTestApp();
    const admin = await loginAsAdmin(app, repository);
    const claim = generateClaim();
    await enroll(app, claim);
    await admin.post(`/api/v1/admin/servers/${SERVER_ID}/approve`);
    await admin.post(`/api/v1/admin/servers/${SERVER_ID}/revoke`);

    const reEnroll = await enroll(app, claim);
    expect(reEnroll.status).toBe(409);
    expect(reEnroll.body).toEqual({ error: 'already_finalized', status: 'revoked' });
  });

  // D6 (allowed case): while still pending, an agent correcting its own
  // enrollment with the SAME claim IS allowed (idempotent metadata
  // update) — this is A3/A7's happy path, and no longer rotates
  // anything (there is nothing left to rotate).
  it('allows correcting hostname/institutionCode while still pending, using the same claim', async () => {
    const { app, repository } = buildTestApp();
    const claim = generateClaim();
    const first = await enroll(app, claim);
    expect(first.status).toBe(202);

    const second = await enroll(app, claim, 'test-bootstrap-secret', enrollBody({ hostname: 'HOUSE-LIMS-02' }));
    expect(second.status).toBe(202);

    const server = repository.getServer(SERVER_ID);
    expect(server?.hostname).toBe('HOUSE-LIMS-02');

    // The same (unchanged) claim keeps working.
    const pollRes = await poll(app, SERVER_ID, claim);
    expect(pollRes.status).toBe(200);
  });

  it('rejects approve attempts with no session', async () => {
    const { app } = buildTestApp();
    await enroll(app, generateClaim());

    const res = await request(app).post(`/api/v1/admin/servers/${SERVER_ID}/approve`);
    expect(res.status).toBe(401);
  });

  it('rejects approve attempts from a viewer-role session', async () => {
    const { app, repository } = buildTestApp();
    await createTestUser(repository, 'viewer', 'test-password', 'viewer');
    const agent = request.agent(app);
    await agent.post('/api/v1/auth/login').send({ username: 'viewer', password: 'test-password' });
    await enroll(app, generateClaim());

    const res = await agent.post(`/api/v1/admin/servers/${SERVER_ID}/approve`);
    expect(res.status).toBe(403);
  });

  it('rejects approving a server that is already approved', async () => {
    const { app, repository } = buildTestApp();
    const admin = await loginAsAdmin(app, repository);
    await enroll(app, generateClaim());
    await admin.post(`/api/v1/admin/servers/${SERVER_ID}/approve`);

    const res = await admin.post(`/api/v1/admin/servers/${SERVER_ID}/approve`);
    expect(res.status).toBe(409);
  });
});

// A5: enrollment being entirely unconfigured (no bootstrap secret set at
// all) is a distinct, discoverable condition from "wrong secret" — both
// enrollment endpoints must say so explicitly (503) rather than a
// misleading 401.
describe('A5: enrollment disabled (no bootstrap secret configured)', () => {
  it('POST /enroll returns 503 enrollment_not_configured', async () => {
    const { app } = buildTestApp({ bootstrapSecret: undefined });
    const res = await enroll(app, generateClaim());
    expect(res.status).toBe(503);
    expect(res.body).toEqual({ error: 'enrollment_not_configured' });
  });

  it('GET /enroll/:serverId returns 503 enrollment_not_configured', async () => {
    const { app } = buildTestApp({ bootstrapSecret: undefined });
    const res = await poll(app, SERVER_ID, generateClaim());
    expect(res.status).toBe(503);
    expect(res.body).toEqual({ error: 'enrollment_not_configured' });
  });

  it('503 takes priority over a present-but-now-meaningless secret/claim', async () => {
    const { app } = buildTestApp({ bootstrapSecret: undefined });
    const res = await enroll(app, generateClaim(), 'some-secret-nobody-can-be-right-about');
    expect(res.status).toBe(503);
  });
});

describe('D5: pending API key TTL', () => {
  it('an expired pending key can no longer be retrieved, even with the correct claim', async () => {
    const { app, repository, db } = buildTestApp();
    const admin = await loginAsAdmin(app, repository);
    const claim = generateClaim();
    await enroll(app, claim);
    await admin.post(`/api/v1/admin/servers/${SERVER_ID}/approve`);

    // Simulate TTL expiry directly rather than sleeping 5 real minutes:
    // backdate expires_at, then let the sweep (also exercised directly)
    // and the check-on-read gate both confirm the key is gone.
    const beforeExpiry = repository.getServer(SERVER_ID);
    expect(beforeExpiry?.pending_api_key).toBeTruthy();
    const past = new Date(Date.now() - 1000).toISOString();
    db.prepare('UPDATE servers SET pending_api_key_expires_at = ? WHERE id = ?').run(past, SERVER_ID);

    const expiredPoll = await poll(app, SERVER_ID, claim);
    expect(expiredPoll.body).toEqual({ status: 'approved' });

    const swept = repository.expirePendingApiKeys(new Date().toISOString());
    expect(swept).toBe(1);
    const server = repository.getServer(SERVER_ID);
    expect(server?.pending_api_key).toBeNull();
    expect(server?.pending_api_key_expires_at).toBeNull();
  });
});
