import { Router } from 'express';
import type { Response } from 'express';
import type { AppConfig } from '../config.js';
import { hashSecret, hashesMatch, secretsMatch } from '../crypto.js';
import type { OperationsRepository, ServerRow } from '../repository.js';
import { EnrollRequest } from '../schemas.js';

// A8 (Wave 2) — the full enrollment/credential state machine, spelled
// out explicitly for any client (including the BRAVO-side agent) built
// against this API:
//
//   pending -> approved         admin-only, POST /admin/servers/:id/approve
//   pending -> revoked          admin-only, POST /admin/servers/:id/revoke
//   approved -> revoked         admin-only, POST /admin/servers/:id/revoke
//   approved/revoked -> approved  admin-only, POST /admin/servers/:id/reissue
//                                 (revoked -> approved is a deliberate,
//                                 explicit un-revoke; never automatic)
//
// There is NO agent self-service path back to 'approved' from
// 'approved' (rotate) or from 'revoked'. An agent holding a stale,
// invalidated, or never-issued API key cannot recover by calling
// POST /enroll again — for an 'approved' or 'revoked' row, POST /enroll
// always returns 409 already_finalized and never mutates the row (see
// repository.upsertPendingServer's 'locked' outcome). The only ways
// back into circulation are (a) an admin reissue, for an existing row,
// or (b) an admin first revoking-then-a-fresh-serverId pending cycle if
// the deployment model calls for retiring the old identity entirely.
// This file/route set does not, and must not, grow a shortcut around
// that — it is intentionally admin-gated.
//
// A1-A3 (fixing PR #2 review finding P1, repository.ts:148 at the time):
// the enrollment claim is generated by the ENROLLING AGENT, sent via
// X-Enrollment-Claim on POST /enroll, and never generated or rotated by
// this server. See repository.upsertPendingServer's doc comment for the
// full rationale and repository.ts:148-history for the vulnerability
// this replaced (server-rotated claim handed back to whoever asked,
// which only required the fleet-wide bootstrap secret + a known/guessed
// serverId to steal).
function claimMatches(server: ServerRow | undefined, claim: string | undefined): boolean {
  if (!server || !claim) {
    return false;
  }
  return hashesMatch(hashSecret(claim), server.enrollment_claim_hash);
}

export function createEnrollRouter(repository: OperationsRepository, config: AppConfig): Router {
  const router = Router();

  // A5: enrollment being entirely unconfigured (no bootstrap secret set)
  // is a distinct condition from "wrong secret" and must not be
  // reported as a 401 — that implies the feature exists and the caller
  // simply got the credential wrong, which is misleading operationally.
  function enrollmentConfigured(res: Response): boolean {
    if (!config.bootstrapSecret) {
      res.status(503).json({ error: 'enrollment_not_configured' });
      return false;
    }
    return true;
  }

  // Self-enrollment (grilling Q17/Q19): the agent generates its own GUID
  // (serverId) AND its own enrollment claim, and calls this
  // unauthenticated-by-identity, secret-gated endpoint.
  // D2: the bootstrap secret travels only via X-Bootstrap-Secret —
  // the same header GET /enroll/:serverId already used.
  // A1/A2: X-Enrollment-Claim is now REQUIRED on POST /enroll too — it's
  // the agent's own freshly generated opaque token, not something the
  // server hands back. Nothing is echoed back in the 202 body anymore
  // (there's nothing left to reveal — the agent already holds its own
  // claim).
  router.post('/enroll', (req, res) => {
    if (!enrollmentConfigured(res)) {
      return;
    }
    if (!secretsMatch(req.header('X-Bootstrap-Secret'), config.bootstrapSecret)) {
      res.status(401).json({ error: 'unauthorized' });
      return;
    }
    const claim = req.header('X-Enrollment-Claim');
    if (!claim) {
      res.status(400).json({ error: 'invalid_request', details: 'X-Enrollment-Claim header is required' });
      return;
    }
    const parsed = EnrollRequest.safeParse(req.body);
    if (!parsed.success) {
      res.status(400).json({ error: 'invalid_request', details: parsed.error.flatten() });
      return;
    }
    const result = repository.upsertPendingServer({
      id: parsed.data.serverId,
      institutionCode: parsed.data.institutionCode,
      productType: parsed.data.productType,
      hostname: parsed.data.hostname,
      claim,
      now: new Date().toISOString(),
    });
    // D6: a repeat POST /enroll for an already-approved/revoked server
    // id is rejected outright rather than silently rewriting identity —
    // see repository.upsertPendingServer's doc comment for why this is
    // the chosen (safe-default) behavior over a claim-gated identity
    // update.
    if (result.outcome === 'locked') {
      res.status(409).json({ error: 'already_finalized', status: result.server.status });
      return;
    }
    // A3: a 'pending' row already has a stored claim hash from its
    // original POST /enroll. A re-POST for the same serverId with a
    // DIFFERENT claim is the takeover attempt this Wave 2 fix closes —
    // it is rejected without mutating the row (original claim/metadata
    // untouched). Only a re-POST with the SAME claim the agent already
    // holds (A7: lost-response recovery) is treated as an idempotent
    // metadata update.
    if (result.outcome === 'claim_mismatch') {
      res.status(409).json({ error: 'claim_mismatch' });
      return;
    }
    res.status(202).json({ status: result.server.status });
  });

  // The agent polls this until an administrator approves it in
  // Operations UI. D3: the API key is retrievable (not reveal-once) for
  // as long as PENDING_KEY_TTL_MS hasn't elapsed since approve/reissue —
  // a same-claim retry recovers from one lost response. D1: both the
  // fleet bootstrap secret AND this server's own enrollment claim
  // (X-Enrollment-Claim, now agent-generated — see A1/A2 above) are
  // required. D7: unknown id, a revoked server, and a present-but-
  // wrong/missing claim all deterministically produce the exact same
  // 404 — nothing here should let a caller distinguish "wrong claim"
  // from "never existed" from "revoked".
  router.get('/enroll/:serverId', (req, res) => {
    if (!enrollmentConfigured(res)) {
      return;
    }
    if (!secretsMatch(req.header('X-Bootstrap-Secret'), config.bootstrapSecret)) {
      res.status(401).json({ error: 'unauthorized' });
      return;
    }
    const server = repository.getServer(req.params.serverId);
    const claim = req.header('X-Enrollment-Claim');
    if (!server || server.status === 'revoked' || !claimMatches(server, claim)) {
      res.status(404).json({ error: 'not_found' });
      return;
    }
    if (server.status !== 'approved') {
      res.status(200).json({ status: server.status });
      return;
    }
    const apiKey = repository.readPendingApiKey(server.id, new Date().toISOString());
    res.status(200).json({ status: server.status, apiKey });
  });

  return router;
}
