import { randomUUID } from 'node:crypto';
import request from 'supertest';
import { beforeEach, describe, expect, it } from 'vitest';
import { buildTestApp, createTestUser } from '../testUtils.js';
import type { OperationsRepository } from '../repository.js';
import type { Express } from 'express';

const SERVER_ID = '22222222-2222-4222-8222-222222222222';

// A1/A2: the claim is now generated by the enrolling caller (here, the
// test itself standing in for the agent), not handed back by the
// server.
function generateTestClaim(): string {
  return `claim_${randomUUID()}`;
}

async function enrollAndApprove(app: Express, repository: OperationsRepository): Promise<string> {
  await createTestUser(repository, 'admin', 'test-password', 'admin');
  const admin = request.agent(app);
  await admin.post('/api/v1/auth/login').send({ username: 'admin', password: 'test-password' });

  const claimToken = generateTestClaim();
  await request(app)
    .post('/api/v1/enroll')
    .set('X-Bootstrap-Secret', 'test-bootstrap-secret')
    .set('X-Enrollment-Claim', claimToken)
    .send({
      serverId: SERVER_ID,
      institutionCode: '01234567',
      productType: 'VETOFFICE',
      hostname: 'HOUSE-VET-01',
    });
  await admin.post(`/api/v1/admin/servers/${SERVER_ID}/approve`);
  const poll = await request(app)
    .get(`/api/v1/enroll/${SERVER_ID}`)
    .set('X-Bootstrap-Secret', 'test-bootstrap-secret')
    .set('X-Enrollment-Claim', claimToken);
  return poll.body.apiKey as string;
}

// Detail-endpoint assertions below need an authenticated session too
// (any role — GET /admin/servers/:id is read-only).
async function loginAsViewer(app: Express, repository: OperationsRepository): Promise<request.SuperAgentTest> {
  await createTestUser(repository, 'viewer', 'test-password', 'viewer');
  const agent = request.agent(app);
  await agent.post('/api/v1/auth/login').send({ username: 'viewer', password: 'test-password' });
  return agent;
}

describe('events + heartbeat ingest', () => {
  let app: Express;
  let repository: OperationsRepository;
  let apiKey: string;

  beforeEach(async () => {
    ({ app, repository } = buildTestApp());
    apiKey = await enrollAndApprove(app, repository);
  });

  it('rejects events without a valid API key', async () => {
    const res = await request(app)
      .post('/api/v1/events')
      .send({ category: 'backup', severity: 'SUCCESS', payload: { message: 'ok' } });
    expect(res.status).toBe(401);
  });

  it('rejects events with a revoked/unknown API key', async () => {
    const res = await request(app)
      .post('/api/v1/events')
      .set('X-Api-Key', 'bop_not-a-real-key')
      .send({ category: 'backup', severity: 'SUCCESS', payload: { message: 'ok' } });
    expect(res.status).toBe(401);
  });

  it('accepts a SUCCESS event even though it carries no problem to report', async () => {
    // Grilling Q18: Operations must receive SUCCESS events too, unlike
    // Discord which can be configured to errors_only.
    const res = await request(app)
      .post('/api/v1/events')
      .set('X-Api-Key', apiKey)
      .send({ category: 'health', severity: 'SUCCESS', payload: { message: 'усі служби працюють' } });
    expect(res.status).toBe(202);
  });

  it('accepts a health event carrying per-service running/stopped status', async () => {
    const res = await request(app)
      .post('/api/v1/events')
      .set('X-Api-Key', apiKey)
      .send({
        category: 'health',
        severity: 'CRITICAL',
        payload: {
          message: 'exchangAPI не запущена',
          services: [
            { name: 'BRAVO', status: 'running' },
            { name: 'exchangAPI', status: 'stopped' },
            { name: 'BRAVO-Web', status: 'unknown' },
          ],
        },
      });
    expect(res.status).toBe(202);

    const viewer = await loginAsViewer(app, repository);
    const detail = await viewer.get(`/api/v1/admin/servers/${SERVER_ID}`);
    expect(detail.body.events).toHaveLength(1);
    expect(detail.body.events[0].category).toBe('health');
    expect(JSON.parse(detail.body.events[0].payload).services).toHaveLength(3);
    expect(detail.body.latestByCategory.health.payload.services).toHaveLength(3);
  });

  it('E5: a retried POST with the same eventId is idempotent (not duplicated)', async () => {
    const body = {
      category: 'backup' as const,
      severity: 'SUCCESS' as const,
      payload: { message: 'генерація завершена' },
      eventId: 'evt-0001',
      occurredAt: '2026-09-24T10:00:00.000Z',
    };
    const first = await request(app).post('/api/v1/events').set('X-Api-Key', apiKey).send(body);
    const retry = await request(app).post('/api/v1/events').set('X-Api-Key', apiKey).send(body);
    expect(first.status).toBe(202);
    expect(retry.status).toBe(202);

    const viewer = await loginAsViewer(app, repository);
    const detail = await viewer.get(`/api/v1/admin/servers/${SERVER_ID}`);
    expect(detail.body.events).toHaveLength(1);
  });

  it('E5: the same eventId from a DIFFERENT server is not treated as a duplicate', async () => {
    const otherServerId = '33333333-3333-4333-8333-333333333333';
    const claimToken = generateTestClaim();
    await request(app)
      .post('/api/v1/enroll')
      .set('X-Bootstrap-Secret', 'test-bootstrap-secret')
      .set('X-Enrollment-Claim', claimToken)
      .send({ serverId: otherServerId, institutionCode: '01234567', productType: 'LIMS', hostname: 'HOUSE-LIMS-02' });
    const admin = request.agent(app);
    await admin.post('/api/v1/auth/login').send({ username: 'admin', password: 'test-password' });
    await admin.post(`/api/v1/admin/servers/${otherServerId}/approve`);
    const poll = await request(app)
      .get(`/api/v1/enroll/${otherServerId}`)
      .set('X-Bootstrap-Secret', 'test-bootstrap-secret')
      .set('X-Enrollment-Claim', claimToken);
    const otherApiKey = poll.body.apiKey as string;

    const body = { category: 'backup' as const, severity: 'SUCCESS' as const, payload: { message: 'shared eventId' }, eventId: 'evt-shared' };
    const resA = await request(app).post('/api/v1/events').set('X-Api-Key', apiKey).send(body);
    const resB = await request(app).post('/api/v1/events').set('X-Api-Key', otherApiKey).send(body);
    expect(resA.status).toBe(202);
    expect(resB.status).toBe(202);

    const viewer = await loginAsViewer(app, repository);
    const detailA = await viewer.get(`/api/v1/admin/servers/${SERVER_ID}`);
    const detailB = await viewer.get(`/api/v1/admin/servers/${otherServerId}`);
    expect(detailA.body.events).toHaveLength(1);
    expect(detailB.body.events).toHaveLength(1);
  });

  it('rejects a malformed event payload (missing message)', async () => {
    const res = await request(app)
      .post('/api/v1/events')
      .set('X-Api-Key', apiKey)
      .send({ category: 'backup', severity: 'SUCCESS', payload: {} });
    expect(res.status).toBe(400);
  });

  it('records a heartbeat and updates last_heartbeat_at', async () => {
    const res = await request(app)
      .post('/api/v1/heartbeat')
      .set('X-Api-Key', apiKey)
      .send({ bravoVersion: '5.3.0' });
    expect(res.status).toBe(202);

    const viewer = await loginAsViewer(app, repository);
    const detail = await viewer.get(`/api/v1/admin/servers/${SERVER_ID}`);
    expect(detail.body.server.last_heartbeat_at).not.toBeNull();
    expect(detail.body.server.bravo_version).toBe('5.3.0');
    expect(detail.body.server.isOnline).toBe(true);
  });
});
